### ISSUE TITLE
Infografía Melissa 

### ISSUE THREAD

**Issue by mel-16** [SistemasTecTlaxiaco/actividad-1-infografia-mel-16#2]
[INFOGRAFIAS TALLER.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-mel-16/files/9437352/INFOGRAFIAS.TALLER.pdf)

**Comment by IrvingFernand0** [comment]
Calificación: 17

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
